### Generate a new pair of tokens for user with ID 1.
GET http://127.0.0.1:8080/access-token?userID=1

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
    client.global.set("expirationTime", response.body.expirationTime);
%}

### Re-generate the pair of tokens for user by 'refreshToken' from above request.
POST http://127.0.0.1:8080/refresh-token
Accept: application/json
Authorization: {{refreshToken}}
Expires: {{expirationTime}}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
    client.global.set("expirationTime", response.body.expirationTime);
%}

### Remove the pair of tokens for user by 'accessToken' from above request.
POST http://127.0.0.1:8080/clear-token
Accept: application/json
Authorization: {{accessToken}}
Expires: {{expirationTime}}
