apiVersion: v1
kind: Service
metadata:
  name: gojwtissuer-service
  labels:
    app: gojwtissuer
spec:
  selector:
    app: gojwtissuer
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30000
      targetPort: 8080
      protocol: TCP
      name: http
