apiVersion: apps/v1
kind: Deployment
metadata:
  name: gojwtissuer-dpl
  namespace: gons
  labels:
    app: gojwtissuer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gojwtissuer
  template:
    metadata:
      labels:
        app: gojwtissuer
    spec:
      containers:
        - name: gojwtissuer
          image: local/dlv-gojwtissuer:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 56268
          securityContext:
            seccompProfile:
              type: Unconfined
            capabilities:
              add:
                - SYS_PTRACE
          env:
            - name: HOST
              value: ""
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"

