apiVersion: apps/v1
kind: Deployment
metadata:
  name: gojwtissuer-dpl
  namespace: gojwtissuer
  labels:
    app: gojwtissuer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gojwtissuer
  template:
    metadata:
      labels:
        app: gojwtissuer
    spec:
      containers:
        - name: gojwtissuer
          image: local/gojwtissuer:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SECRET_KEY
              value: "secretkey"
            - name: PORT
              value: "8080"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "secret"

