apiVersion: apps/v1
kind: Deployment
metadata:
  name: gojwtissuer-dpl
  namespace: gons
  labels:
    app: gojwtissuer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gojwtissuer
  template:
    metadata:
      labels:
        app: gojwtissuer
    spec:
      containers:
        - name: gojwtissuer
          image: local/gojwtissuerdlv:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 56268
          securityContext:
            seccompProfile:
              type: Unconfined
            capabilities:
              add:
                - SYS_PTRACE
          env:
            - name: HOST
              value: ""
            - name: PORT
              value: "8080"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "secret"
            - name: SECRET_KEY
              value: "secretkey"
            - name: AUDIENCE_AUD
              value: "jwt.account.local"
            - name: ISSUER_ISS
              value: "jwt.local"
            - name: EXPIRATION_TIME_EXP
              value: "10"
