apiVersion: apps/v1
kind: Deployment
metadata:
  name: gojwtissuer-deployment
  labels:
    app: gojwtissuer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gojwtissuer
  template:
    metadata:
      labels:
        app: gojwtissuer
    spec:
      containers:
        - name: gojwtissuer-deployment
          image: local/gojwtissuer
          ports:
            - containerPort: 8080
          env:
            - name: SECRET_KEY
              value: "secretkey"
            - name: PORT
              value: "8080"
