apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: gons
  labels:
    app: gojwtissuer
spec:
  containers:
    - name: redis-server
      image: redis:7.0
      command:
        - redis-server
        - "/redis-master/redis.conf"
      env:
        - name: MASTER
          value: "true"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: redis
      args:
        - --requirepass
        - $(REDIS_PASSWORD)
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: redis
        items:
          - key: redis-config
            path: redis.conf
