apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: gojwtissuer
  labels:
    app: gojwtissuer
spec:
  type: ClusterIP
  selector:
    app: gojwtissuer
  ports:
    - port: 6379
      targetPort: 6379
      name: redis


