apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: gojwtissuer
  labels:
    app: gojwtissuer
spec:
  type: NodePort
  selector:
    app: gojwtissuer
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30001
      name: redis


