apiVersion: v1
kind: Service
metadata:
  name: gojwtissuer
  namespace: gojwtissuer
  labels:
    app: gojwtissuer
spec:
  type: NodePort
  selector:
    app: gojwtissuer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
      name: http
