apiVersion: v1
kind: Service
metadata:
  name: gojwtissuer-srv
  namespace: gojwtissuer
  labels:
    app: gojwtissuer
spec:
  selector:
    app: gojwtissuer
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30000
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 6379
      nodePort: 30001
      targetPort: 6379
      protocol: TCP
      name: redis
