apiVersion: v1
kind: Service
metadata:
  name: gojwtissuer
  namespace: gons
  labels:
    app: gojwtissuer
spec:
  type: LoadBalancer
  selector:
    app: gojwtissuer
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 56268
      targetPort: 56268
      name: dlv
